//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietsanpham
    {
        public int ID_SanPham { get; set; }
        public Nullable<int> NamSX { get; set; }
        public string XuatXu { get; set; }
        public string TenHang { get; set; }
        public string ThongSoKyThuat { get; set; }
        public Nullable<int> ThoiHanBaoHanh { get; set; }
    
        public virtual sanpham sanpham { get; set; }
    }
}
