//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiethoadon
    {
        public int ID_HoaDon { get; set; }
        public int ID_LoHang { get; set; }
        public int SoLuongMua { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public int DonGia { get; set; }
    
        public virtual hoadon hoadon { get; set; }
        public virtual kho kho { get; set; }
    }
}
