//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhaphang
    {
        public int ID_LoHang { get; set; }
        public int ID_SanPham { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public int SoLuongNhap { get; set; }
        public int GiaMua { get; set; }
    
        public virtual kho kho { get; set; }
    }
}
