//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtinbaohanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thongtinbaohanh()
        {
            this.lichsubaohanhs = new HashSet<lichsubaohanh>();
        }
    
        public int ID_BaoHanh { get; set; }
        public int ID_HoaDon { get; set; }
        public int ID_LoHang { get; set; }
        public int ID_SanPham { get; set; }
        public Nullable<System.DateTime> HanBaoHanh { get; set; }
        public string Serial { get; set; }
    
        public virtual hoadon hoadon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lichsubaohanh> lichsubaohanhs { get; set; }
    }
}
